<?php

namespace Modules\Easybill\app\Helper;

use Illuminate\Support\Facades\Http;

class DataMapping
{
    
    public function mapCustomer($customer, $addresses, $countries) {
        $customerData = [
            'acquire_options'               =>  null,
            'additional_groups_ids'         =>  [],
            'archived'                      =>  false,
            'bank_account'                  =>  null,
            'bank_account_owner'            =>  null,
            'bank_bic'                      =>  null,
            'bank_code'                     =>  null,
            'bank_iban'                     =>  null,
            'bank_name'                     =>  null,
            'birth_date'                    =>  '' ,
            'buyer_reference'               =>  '' ,                        // thought was said that customer will have this field?
            'cash_allowance'                =>  null,
            'cash_allowance_days'           =>  $customer->payment_time,
            'cash_discount'                 =>  null,
            'cash_discount_type'            =>  null,
            'city'                          =>  $addresses['is_billing']->city,
            'company_name'                  =>  $customer->company_name,
            'country'                       =>  $countries[$addresses['is_billing']->country_id ?? 276]->alpha_2_code ?? 'DE',
            'court'                         =>  'Amtsgericht Köln',
            'court_registry_number'         =>  'HRB 96845',
            'created_at'                    =>  $customer->created_at->format('d.m.Y'),
            'delivery_city'                 =>  $addresses['is_delivery']->city ?? '',
            'delivery_company_name'         =>  $addresses['is_delivery']->company_name ?? '',
            'delivery_country'              =>  $countries[$addresses['is_delivery']->country_id ?? 276]->alpha_2_code ?? 'DE',
            'delivery_first_name'           =>  $addresses['is_delivery']->first_name ?? '',  
            'delivery_last_name'            =>  $addresses['is_delivery']->last_name ?? '',
            'delivery_personal'             =>  false,
            'delivery_salutation'           =>  0,
            'delivery_state'                =>  '',
            'delivery_street'               =>  $addresses['is_delivery']->street ?? '',
            'delivery_suffix_1'             =>  null,
            'delivery_suffix_2'             =>  null,
            'delivery_title'                =>  '',
            'delivery_zip_code'             =>  $addresses['is_delivery']->zip_code ?? '',
            'display_name'                  =>  $customer->company_name,
            'document_pdf_type'             =>  'default',
            'due_in_days'                   =>  null,
            'emails' =>  [
                'buchhaltung@simplelogistik.de'
            ],
            'fax'                           =>  null,
            'first_name'                    =>  $addresses['is_billing']->first_name ?? $customer->first_name,
            'foreign_supplier_number'       =>  '',
            'grace_period'                  =>  null,
            'group_id'                      =>  null,
            'info_1'                        =>  null,
            'info_2'                        =>  null,
            'internet'                      =>  'https://www.simplelogistik.de',
            'last_name'                     =>  $addresses['is_billing']->last_name ?? $customer->last_name,
            'login_id'                      =>  $customer->internal_id,
            'mobile'                        =>  null,
            'note'                          =>  null,
            'number'                        =>  $customer->internal_id,
            'payment_options'               =>  null,
            'personal'                      =>  false,
            'phone_1'                       =>  $addresses['is_billing']->phone ?? $customer->phone,
            'phone_2'                       =>  null,
            'postbox'                       =>  null,
            'postbox_city'                  =>  null,
            'postbox_country'               =>  null,
            'postbox_state'                 =>  '',
            'postbox_zip_code'              =>  null,
            'sale_price_level'              =>  null,
            'salutation'                    =>  1,
            'sepa_agreement'                =>  null,
            'sepa_agreement_date'           =>  null,
            'sepa_mandate_reference'        =>  '',
            'since_date'                    =>  null,      
            'state'                         =>  '',
            'street'                        =>  $addresses['is_billing']->street ?? '',
            'suffix_1'                      =>  null,
            'suffix_2'                      =>  null,
            'tax_number'                    =>  null,
            'tax_options'                   =>  null,
            'title'                         =>  null,
            'updated_at'                    =>  $addresses['is_billing']->updated_at->format('d.m.Y') ?? $customer->updated_at->format('d.m.Y'),
            'vat_identifier'                =>  $customer->tax_number,
            'zip_code'                      =>  $addresses['is_billing']->zip ?? '' 
        ];
        return $customerData;
    }

    public function mapOrder($order, $customer, $addresses) {
        $orderData = [
            'bank_debit_form'       => null,
            'calc_vat_from'         => 0,
            'cash_allowance'        => null,
            'cash_allowance_days'   => 7,
            'cash_allowance_text'   => null,
            'contact_id'            => null,
            'contact_label'         => '',
            'contact_text'          => '',
            'currency'              => 'EUR',
            'customer_id'           => 2035981467,
            'discount'              => null,
            'discount_type'         => null,
            'document_date'         => '2024-01-12',
            'external_id'           => null,
            'replica_url'           => null,
            'grace_period'          => null,
            'due_in_days'           => null,
            'is_acceptable_on_public_domain' => false,
            'is_archive'            => false,
            'is_replica'            => false,
            'is_oss'                => false,
            'items' => [
                'number'                => 'Palette',
                'description'           => 'Transport Hannover-München',
                'document_note'         => 'Transportkosten Auftr. 345',
                'quantity'              => 3,
                'quantity_str'          => 3,
                'unit'                  => null,
                'type'                  => 'POSITION',
                'position'              => null,
                'single_price_net'      => 23500,
                'single_price_gross'    => null,
                'vat_percent'           => 19,
                'discount'              => null,
                'discount_type'         => null,
                'position_id'           => 1,
                'booking_account'       => null,
                'export_cost_1'         => null,
                'export_cost_2'         => null,
                'cost_price_net'        => null,
                'itemType'              => 'UNDEFINED'
            ],
            'login_id'          => null,
            'number'            => 86604,
            'order_number'      => '202401_00010',
            'buyer_reference'   => '',
            'pdf_template'      => '316947',
            'project_id'        => null,
            'recurring_options' => [
                'next_date'                 => '',
                'frequency'                 => '',
                'frequency_special'         => null,
                'interval'                  => 1,
                'end_date_or_count'         => null,
                'status'                    => 'WAITING',
                'as_draft'                  => false,
                'is_notify'                 => false,
                'send_as'                   => null,
                'is_sign'                   => false,
                'is_paid'                   => false,
                'paid_date_option'          => 'created_date',
                'is_sepa'                   => false,
                'sepa_local_instrument'     => null,
                'sepa_sequence_type'        => null,
                'sepa_reference'            => null,
                'sepa_remittance_information' => null,
                'target_type'               => '316947'
            ],
            'ref_id'        => null,
            'service_date'  => [
                'type'          => 'DEFAULT',
                'date'          => '2024-01-11',
                'date_from'     => null,
                'date_to'       => null,
                'text'          => null
            ],
            'shipping_country'      => null,
            'status'                => null,
            'text'                  => 'Vielen Dank für Ihren Auftrag!\n\nBitte begleichen Sie den offenen Betrag bis zum %DOKUMENT.DATUM-FAELLIG%.\n\nMit freundlichen Grüßen\n\n%FIRMA.FIRMA%\n',
            'text_prefix'           => '%KUNDE.ANREDE%,\nnachfolgend berechnen wir Ihnen wie vorab besprochen =>\n',
            'text_tax'              => null,
            'title'                 => 'Invoice for Order #010',
            'type'                  => 'INVOICE',
            'use_shipping_address'  => false,
            'vat_country'           => null,
            'fulfillment_country'   => null,
            'vat_option'            => null,
            'file_format_config' => [
                'type' => 'default'
            ]
        ];
        return $orderData;
    }
}