const headers = [
    {
        show: true,
        key: "id", 
        text: 'label.id',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    // {
    //     show: false,
    //     key: "forwarder_id", 
    //     text: 'label.forwarder_id',
    //     sortable: true,
    //     searchable: true, 
    //     filterable: true,
    // },
    {
        show: true,
        key: "address_id", 
        text: 'label.address_id',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "name", 
        text: 'label.name',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "max_weight", 
        text: 'label.max_weight',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_weight", 
        text: 'label.max_pickup_weight',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_width", 
        text: 'label.max_pickup_width',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_height", 
        text: 'label.max_pickup_height',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_length", 
        text: 'label.max_pickup_length',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "vehicle_type", 
        text: 'label.vehicle_type',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: true,
        key: "plate_number", 
        text: 'label.plate_number',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: false,
        key: "created_at", 
        text: 'label.created_at',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
    {
        show: false,
        key: "updated_at", 
        text: 'label.updated_at',
        sortable: true,
        searchable: true, 
        filterable: true,
    },
];


export default headers;