const headers = [
    {
        show: false,
        key: "id", 
        text: 'labels.id',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "address_id", 
        text: 'labels.address_id',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "name", 
        text: 'labels.vehicle_name',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_weight", 
        text: 'labels.max_weight',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_weight", 
        text: 'labels.max_pickup_weight',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_width", 
        text: 'labels.max_pickup_width',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_height", 
        text: 'labels.max_pickup_height',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_length", 
        text: 'labels.max_pickup_length',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "vehicle_type", 
        text: 'labels.vehicle_type',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "plate_number", 
        text: 'labels.plate_number',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "created_at", 
        text: 'labels.created_at',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "updated_at", 
        text: 'labels.updated_at',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
];


export default headers;