import parcelEmpty from '@/Pages/Parcels/CreateEditParcel/parcelEmpty.js';
import addressEmpty from '@/Pages/Addresses/CreateEditAddress/addressEmpty.js';
export default {
    id: '',
    description: '',
    type_of_transport: '',
    origin: '',
    customer_reference: '',
    shipping_price: '',
    shipping_price_netto: '',
    provision: '',
    order_edited_events: '',
    customer_id: '',
    contact_id: '',
    pickup_address_id: '',
    delivery_address_id: '',
    avis_customer_phone: '',
    avis_sender_phone: '',
    avis_receiver_phone: '',
    p_calculation_model_name: '',
    p_order_number: '',
    p_order_pdf: '',
    p_payment_method: '',
    p_date_of_sale: '',
    p_date_of_cancellation: '',
    p_pickup_date_from: '',
    p_pickup_date_to: '',
    p_pickup_comments: '',
    p_delivery_date_from: '',
    p_delivery_date_to: '',
    p_delivery_comments: '',
    p_description_of_transport: '',
    p_particularities: '',
    p_loading_meter: '',
    p_square_meter: '',
    p_total_weight: '',
    p_qubic_meter: '',
    p_calculated_transport_price: '',
    p_transport_price_gross: '',
    p_transport_price_vat: '',
    p_transport_price_net: '',
    p_customized_price_change: '',
    p_customized_price_mode: '',
    p_discount: '',
    p_price_gross: '',
    p_price_vat: '',
    p_price_net: '',
    p_price_fuel_surcharge: '',
    p_vat_rate: '',
    p_value_insured: '',
    p_value_of_goods: '',
    p_distance_km: '',
    p_duration_minutes: '',
    parcels: [
        parcelEmpty,
        parcelEmpty,
    ],
    pickup_address: addressEmpty,
    delivery_address: addressEmpty,
}