export default {
    company_name: null,
    first_name: null,
    last_name: null,
    address_type: null,
    street: "",
    house_number: null,
    zip_code: "",
    city: "",
    country_code: "",
    email: null,
    phone: null,
    state: null,
    type_of_address: null,
    address_additional_information: null,
    customer_id: null,
    forwarder_id: null,
}