sessionStorage.removeItem('addresses-table-headers')
sessionStorage.removeItem('orders-table-headers')
sessionStorage.removeItem('customers-table-headers')
sessionStorage.removeItem('documents-table-headers')
sessionStorage.removeItem('invoices-table-headers')
sessionStorage.removeItem('forwarders-table-headers')
sessionStorage.removeItem('vehicles-table-headers')

sessionStorage.removeItem('address-table-headers')
sessionStorage.removeItem('order-table-headers')
sessionStorage.removeItem('customer-table-headers')
sessionStorage.removeItem('document-table-headers')
sessionStorage.removeItem('invoice-table-headers')
sessionStorage.removeItem('forwarder-table-headers')
sessionStorage.removeItem('vehicle-table-headers')