export default  {
    company_name: 'Random text',
    first_name: 'Random text',
    last_name: 'Random text',
    address_type: 'Main headquarters',
    street: "Random text",
    house_number: 'Random text',
    zip_code: "Random text",
    city: "Random text",
    country: "Random text",
    state: 'Random text',
    type_of_address: '',
    comment: 'Random text',
    customer_id: 1,
    forwarder_id: 1,
}