const headers = [
    {
        show: true,
        key: "id", 
        contentConfig: {
            type: 'link',
            use: "id",
            to: 'vehicles.edit'
        },
        title: 'tables.vehicles.headers.id',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "address_id", 
        title: 'tables.vehicles.headers.address_id',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "name", 
        title: 'tables.vehicles.headers.vehicle_name',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_weight", 
        title: 'tables.vehicles.headers.max_weight',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_weight", 
        title: 'tables.vehicles.headers.max_pickup_weight',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_width", 
        title: 'tables.vehicles.headers.max_pickup_width',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_height", 
        title: 'tables.vehicles.headers.max_pickup_height',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "max_pickup_length", 
        title: 'tables.vehicles.headers.max_pickup_length',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "vehicle_type", 
        title: 'tables.vehicles.headers.vehicle_type',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: true,
        key: "plate_number", 
        title: 'tables.vehicles.headers.plate_number',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "created_at", 
        title: 'tables.vehicles.headers.created_at',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
    {
        show: false,
        key: "updated_at", 
        title: 'tables.vehicles.headers.updated_at',
        sortable: true,
        searchable: true,
        search_key: '',
        filterable: true,
    },
];


export default headers;